### ISSUE TITLE
Consider psychic as an addition

### ISSUE THREAD

**Issue by Redirts** [kyrolabs/awesome-langchain#21]
Would you consider adding https://github.com/psychic-api/psychic to the list?

Psychic is an open source integration platform to extract and transform unstructured data from SaaS applications like Notion, Slack, Zendesk, Confluence, and Google Drive. Instead of building one integration for each data source, you can build one integration that works for all data sources, and manage each connection from a GUI.

**Comment by sbusso** [comment]
yes 👍🏻
