### ISSUE TITLE
a repo you might want to add (generate mindmap with langchain)

### ISSUE THREAD

**Issue by xianjianlf2** [kyrolabs/awesome-langchain#31]
[MindGeniusAI](https://github.com/xianjianlf2/MindGeniusAI)

Hi, I have a great project that I would like to add to the list. The project is a LangchainJs-based tool that can help users quickly generate mind maps using chatGPT.
If this is awesome enough,please add it to your list 😁
Thanks!

**Comment by sbusso** [comment]
Thanks @xianjianlf2 for the suggestion, link added.
