### ISSUE TITLE
Add learning resource

### ISSUE THREAD

**Issue by Redirts** [kyrolabs/awesome-langchain#32]
Hi,

Should we add this: [https://blog.bytebytego.com/p/how-to-build-a-smart-chatbot-in-10](https://blog.bytebytego.com/p/how-to-build-a-smart-chatbot-in-10) ?

It's a paid article but there is a free trial and from what I read it looks well written

**Comment by sbusso** [comment]
Hey thanks for the suggestion. Being accessible and open is the core of this list, so we will need to pass on this article.
