### ISSUE TITLE
Two repos you might want to add

### ISSUE THREAD

**Issue by pors** [kyrolabs/awesome-langchain#8]
Hi, I created two langchain related projects:

* LangChain chat with streaming response over FastAPI websockets: https://github.com/pors/langchain-chat-websockets

* FastAPI LangChain Nextjs clients: https://github.com/pors/langchain-clients

If they are awesome enough, please add them to your list 😁
I'm happy to provide a PR if you tell me what category they fit best.

**Comment by sbusso** [comment]
Hey @pors, good question about the category. How do you see those clients compared to the existing ones in langchain and in the deployment services section (which would deserve a better title) and how people would use those repos?

**Comment by pors** [comment]
Hey @sbusso. These repos are like starter code for your projects. The first includes a backend and a demo frontend client. So it could be in the open source projects? Or maybe a new category "starter packs".

The second one is a frontend complement for the langcorn backend you have already listed, so maybe mention it there?

**Comment by pors** [comment]
Great you are doing this BTW, very helpful!

**Comment by sbusso** [comment]
Thanks. I added the websocket example. Could the Langcorn examples join the other examples on Langcorn repo?

**Comment by pors** [comment]
Thanks, yeah that might be a good idea.
